local g = vim.g
local o = vim.o
local opt = vim.opt
--o.termguicolors = true
o.timeoutlen = 500
o.updatetime = 200
o.scrolloff = 8
o.number = true
o.numberwidth = 2
o.relativenumber = true
o.cursorline = false
o.expandtab = true
o.smarttab = true
o.cindent = true
o.autoindent = true
o.wrap = true
o.textwidth = 300
o.tabstop = 4
o.shiftwidth = 4
o.softtabstop = -1 
o.list = true
o.listchars = "trail:·,nbsp:◇,tab:→ ,extends:▸,precedes:◂"
o.clipboard = "unnamedplus"
o.ignorecase = true
o.smartcase = true
o.backup = false
o.writebackup = false
o.undofile = true
o.swapfile = false
o.history = 50
o.splitright = true
o.splitbelow = true
opt.mouse = "a"
g.mapleader = " "
g.maplocalleader = " "
opt.backspace = '2'
opt.showcmd = true
opt.laststatus= 2
opt.autowrite = true
opt.autoread = true
opt.shiftround = true
opt.iskeyword:append("-")

