# /* ----------- 💫 https://github.com/JaKooLit 💫 -------- */ #

[pyprland]

plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
lazy = true
unfocus = "hide"


[scratchpads.rangerf]
animation = "fromTop"
command = "kitty --class rangerf -e ranger"
class = "rangerf"
lazy = true
unfocus = "hide"
size = "60% 60%"

[scratchpads.ncmpcpp]
animation = "fromTop"
command = "kitty --class ncmpcpp -e ncmpcpp"
class = "ncmpcpp"
lazy = true
unfocus = "hide"
size = "60% 60%"

[scratchpads.music]
animation = "fromTop"
command = "youtube-music"
class = "com.github.th_ch.youtube_music"
lazy = true
unfocus = "hide"
size = "60% 60%"

[scratchpads.pavucontrol]
animation = "fromTop"
command = "pavucontrol"
class = "Pavucontrol"
lazy = true
unfocus = "hide"
size = "60% 60%"

[scratchpads.bluetooth]
animation = "fromTop"
command = "blueman-manager"
class = "blueman-manager"
lazy = true
unfocus = "hide"
size = "60% 60%"

[scratchpads.ticktick]
animation = "fromTop"
command = "ticktick"
class = "ticktick"
lazy = true
unfocus = "hide"
size = "60% 60%"


[scratchpads.message]
animation = "fromTop"
command = "wasistlos"
class = "wasistlos"
lazy = true
unfocus = "hide"
size = "60% 60%"

